### ISSUE TITLE
OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by MrDevil131** [Galiafer/Telegram-Shop#1]
Добрый день! Заранее прошу прощения, если что-то делаю не так - гитхабом пользуюсь не слишком часто, про ошибку пишу в первый раз.
Питон 3.7, вин10. С установкой проблем не возникло, функционал весь рабочий и полностью устраивает, но при остановке бота из окна телеграма получаю трейсбак:

`
Traceback (most recent call last):
  File "C:\Users\7001\AppData\Local\Programs\Python\Python37\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 385, in start_polling
    allowed_updates=allowed_updates
  File "C:\Users\7001\AppData\Local\Programs\Python\Python37\lib\site-packages\aiogram\bot\bot.py", line 111, in get_updates
    return [types.Update(**update) for update in result]
  File "C:\Users\7001\AppData\Local\Programs\Python\Python37\lib\site-packages\aiogram\bot\bot.py", line 111, in <listcomp>
    return [types.Update(**update) for update in result]
  File "C:\Users\7001\AppData\Local\Programs\Python\Python37\lib\site-packages\aiogram\types\base.py", line 95, in __init__
    self.props[key].set_value(self, value, parent=self)
  File "C:\Users\7001\AppData\Local\Programs\Python\Python37\lib\site-packages\aiogram\types\fields.py", line 57, in set_value
    value = self.deserialize(value, parent)
  File "C:\Users\7001\AppData\Local\Programs\Python\Python37\lib\site-packages\aiogram\types\fields.py", line 115, in deserialize
    return self.base_object.to_object(conf={'parent': parent}, data=value)
  File "C:\Users\7001\AppData\Local\Programs\Python\Python37\lib\site-packages\aiogram\types\base.py", line 153, in to_object
    return cls(conf=conf, **data)
  File "C:\Users\7001\AppData\Local\Programs\Python\Python37\lib\site-packages\aiogram\types\base.py", line 95, in __init__
    self.props[key].set_value(self, value, parent=self)
  File "C:\Users\7001\AppData\Local\Programs\Python\Python37\lib\site-packages\aiogram\types\fields.py", line 57, in set_value
    value = self.deserialize(value, parent)
  File "C:\Users\7001\AppData\Local\Programs\Python\Python37\lib\site-packages\aiogram\types\fields.py", line 115, in deserialize
    return self.base_object.to_object(conf={'parent': parent}, data=value)
  File "C:\Users\7001\AppData\Local\Programs\Python\Python37\lib\site-packages\aiogram\types\chat_member.py", line 97, in to_object
    return cls.resolve(conf=conf, **data)
  File "C:\Users\7001\AppData\Local\Programs\Python\Python37\lib\site-packages\aiogram\types\chat_member.py", line 88, in resolve
    return class_(**kwargs)
  File "C:\Users\7001\AppData\Local\Programs\Python\Python37\lib\site-packages\aiogram\types\base.py", line 95, in __init__
    self.props[key].set_value(self, value, parent=self)
  File "C:\Users\7001\AppData\Local\Programs\Python\Python37\lib\site-packages\aiogram\types\fields.py", line 57, in set_value
    value = self.deserialize(value, parent)
  File "C:\Users\7001\AppData\Local\Programs\Python\Python37\lib\site-packages\aiogram\types\fields.py", line 175, in deserialize
    return datetime.datetime.fromtimestamp(value)
OSError: [Errno 22] Invalid argument
`

После ошибки бот перестает реагировать на что-либо. Если закрыть и заново открыть main.py и попробовать перезапустить бот (именно если перезапустить, потому как если просто жму /start, с другого аккаунта, где его не блокировал, всё ок,) получаю ту же ошибку. 
Заранее спасибо за помощь!

**Comment by MrDevil131** [comment]
Ошибка ушла при смене версии питона с 3.7 на 3.9
